apiVersion: v1
data:
  settings.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"
    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0
    https://maven.apache.org/xsd/settings-1.0.0.xsd\">\n  <localRepository></localRepository>\n
    \ <profiles>\n    <profile>\n      <id>maven-settings</id>\n      <activation>\n
    \       <activeByDefault>true</activeByDefault>\n      </activation>\n      \n
    \     <repositories>\n        <repository>\n          <id>central</id>\n          <name>Maven
    Central</name>\n          <url>https://repo.maven.apache.org/maven2/</url>\n        </repository>\n
    \       <repository>\n          <id>jboss-ea</id>\n          <name>JBoss Early
    Access</name>\n          <url>https://repository.jboss.org/nexus/content/groups/ea/</url>\n
    \       </repository>\n        <repository>\n          <id>redhat-ga</id>\n          <name>Red
    Hat General Availability Repository</name>\n          <url>https://maven.repository.redhat.com/ga/</url>\n
    \       </repository>\n        <repository>\n        <id>indy</id>\n        <url>http://indy.psi.redhat.com/api/content/maven/group/pnc-builds/</url>\n
    \       <snapshots>\n            <enabled>false</enabled>\n        </snapshots>\n
    \       <releases>\n            <enabled>true</enabled>\n        </releases>\n
    \   </repository>\n      </repositories>\n    \n      <pluginRepositories>\n        <pluginRepository>\n
    \         <id>central</id>\n          <name>Maven Central</name>\n          <url>https://repo.maven.apache.org/maven2/</url>\n
    \       </pluginRepository>\n        <pluginRepository>\n          <id>jboss-ea</id>\n
    \         <name>JBoss Early Access</name>\n          <url>https://repository.jboss.org/nexus/content/groups/ea/</url>\n
    \       </pluginRepository>\n        <pluginRepository>\n          <id>redhat-ga</id>\n
    \         <name>Red Hat General Availability Repository</name>\n          <url>https://maven.repository.redhat.com/ga/</url>\n
    \       </pluginRepository>\n        <pluginRepository>\n            <id>indy</id>\n
    \           <url>http://indy.psi.redhat.com/api/content/maven/group/pnc-builds/</url>\n
    \           <snapshots>\n                <enabled>false</enabled>\n            </snapshots>\n
    \           <releases>\n                <enabled>true</enabled>\n            </releases>\n
    \       </pluginRepository>\n      </pluginRepositories>\n  \n    </profile>\n
    \ </profiles>\n</settings>"
kind: ConfigMap
metadata:
  labels:
    app: camel-k
  name: camel-k-maven-settings
